#version 450

layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba32f, binding = 0) uniform writeonly image2D u_Output;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size  = imageSize(u_Output);

    if (pixel.x >= size.x || pixel.y >= size.y)
        return;

    /* Normalized UV (0 -> 1) */
    vec2 uv = vec2(pixel) / vec2(size);

    vec4 color = vec4(uv.x, uv.y, 0.0, 1.0);

    imageStore(u_Output, pixel, color);
}